export const profileDescriptions = [
  "Desenvolvedor",
  "Programador",
  "Pai de pet",
  "Gamer",
  "Entusiasta de Tecnologia",
  "Amante da Música",
  "Fotógrafo Amador",
  "Cozinheiro de Fim de Semana",
  "Leitor Ávido",
  "Café Lover",
  "Explorador Urbano",
  "Ciclista",
  "Viajante",
  "Cineasta",
  "Designer Gráfico",
  "Criativo",
  "Inovador",
  "Empreendedor",
  "Solucionador de Problemas",
  "Analítico",
  "Pensador Crítico",
  "Comunicação Eficaz",
  "Colaborador",
  "Líder",
  "Motivador",
  "Organizado",
  "Detalhista",
  "Proativo",
  "Adaptável",
  "Resiliente",
  "Curioso",
  "Aprendiz Constante",
  "Artista Digital",
  "Engenheiro de Software",
  "Especialista em Segurança",
  "Jogador de Equipe",
  "Educador",
  "Mentor",
  "Estratégico",
  "Gerente de Projetos",
  "Ator",
  "Blogger",
  "Vlogger",
  "Podcaster",
  "Escritor",
  "Poeta",
  "Jardineiro",
  "Maratonista",
  "Triatleta",
  "Instrutor de Yoga",
  "Voluntário",
  "Ativista",
  "Consultor",
  "Treinador",
  "Nutricionista",
  "Chef de Cozinha",
  "Sommelier",
  "Artista Plástico",
  "Músico",
  "DJ",
  "Produtor de Música",
  "Coreógrafo",
  "Dançarino",
  "Aventureiro",
  "Escoteiro",
  "Pescador",
  "Montanhista",
  "Astrônomo Amador",
  "Historiador",
  "Genealogista",
  "Programador de Jogos",
  "Desenvolvedor Full-Stack",
  "Especialista em UI/UX",
  "Criador de Conteúdo",
  "Redator Técnico",
  "Marketing Digital",
  "Especialista em SEO",
  "Gerente de Comunidade",
  "Designer de Interiores",
  "Arquiteto",
  "Urbanista",
  "Advogado",
  "Engenheiro Civil",
  "Engenheiro Mecânico",
  "Consultor Financeiro",
  "Investidor",
  "Colecionador de Arte",
  "Antiquário",
  "Restaurador",
  "Mecânico de Automóveis",
  "Especialista em TI",
  "Administrador de Sistemas",
  "Administrador de Redes",
  "Desenvolvedor Front-End",
  "Desenvolvedor Back-End",
  "Animador 3D",
  "Ilustrador",
  "Cartunista",
  "Designer de Moda",
  "Costureiro",
  "Estilista",
  "Maquiador",
  "Cabeleireiro",
  "Barbeiro",
  "Consultor de Imagem",
  "Personal Stylist",
  "Personal Trainer",
  "Instrutor de Fitness",
  "Professor de Educação Física",
  "Nutricionista Esportivo",
  "Fisioterapeuta",
  "Terapeuta Ocupacional",
  "Psicólogo",
  "Psiquiatra",
  "Médico",
  "Dentista",
  "Veterinário",
  "Biólogo",
  "Ecologista",
  "Ambientalista",
  "Engenheiro Ambiental",
  "Químico",
  "Físico",
  "Matemático",
  "Estatístico",
  "Analista de Dados",
  "Cientista de Dados",
  "Engenheiro de Dados",
  "Especialista em Inteligência Artificial",
  "Especialista em Machine Learning",
  "Roboticista",
  "Engenheiro Eletrônico",
  "Engenheiro Elétrico",
  "Engenheiro de Telecomunicações",
  "Especialista em Blockchain",
  "Criptógrafo",
  "Engenheiro de Som",
  "Técnico de Som",
  "Produtor de Vídeo",
  "Editor de Vídeo",
  "Cinegrafista",
  "Fotógrafo de Natureza",
  "Fotógrafo de Eventos",
  "Fotógrafo de Moda",
  "Fotógrafo de Produtos",
  "Fotógrafo de Retratos",
  "Fotógrafo de Casamentos",
  "Fotógrafo de Bebês",
  "Fotógrafo de Animais",
  "Fotógrafo de Esportes",
  "Fotógrafo Subaquático",
  "Fotógrafo Aéreo",
  "Fotógrafo Documental",
  "Fotógrafo de Rua",
  "Fotógrafo Conceitual",
  "Fotógrafo Fine Art",
];
