export const profileDescriptions = [
  "Desenvolvedor Full Stack",
  "Café Lover",
  "Entusiasta de Tecnologia",
  "Pai de Pet",
  "Admirador de Gadgets",
  "Entusiasta de Open Source",
  "Fã de Hacking Ético",
  "Desenvolvedor Frontend",
  "Especialista em Segurança Cibernética",
  "Programador",
  "Engenheiro de Software",
  "Analista de Sistemas",
  "Garoto de progarama",
  "Gamer",
  "Nerd de TI",
  "Desenvolvedor Backend",
  "Ávido por Inovação Tecnológica",
  "Desenvolvedor Web",
  "Cozinheiro de Fim de Semana",
  "Aficionado por Código",
];
